### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by xgnusr** [rrwick/CNN-Demultiplexer#14]
Hello, after installing Deepbinner:

.......
usr@pandora:/test/Deepbinner/models$ deepbinner classify -s SQK-RBK004_read_starts input
Using TensorFlow backend.
Loading SQK-RBK004_read_starts... done
Error: input is neither a file nor a directory
.......

Another try:

usr@pandora:/albacore/gridion/basecalled/01010102/GA10000$ deepbinner classify --rapid /albacore/gridion/basecalled/01010102/GA10000/reads/0/ > classifications
Using TensorFlow backend.
2018-11-09 15:13:00.956983: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Loading /usr/local/lib/python3.6/site-packages/deepbinner/models/SQK-RBK004_read_starts... Traceback (most recent call last):
  File "/usr/local/bin/deepbinner", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/deepbinner/deepbinner.py", line 60, in main
    classify(args)
  File "/usr/local/lib/python3.6/site-packages/deepbinner/classify.py", line 36, in classify
    load_and_check_models(args.start_model, args.end_model, args.scan_size)
  File "/usr/local/lib/python3.6/site-packages/deepbinner/classify.py", line 66, in load_and_check_models
    out_dest=out_dest)
  File "/usr/local/lib/python3.6/site-packages/deepbinner/classify.py", line 90, in load_trained_model
    model = load_model(model_file)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/saving.py", line 417, in load_model
    f = h5dict(filepath, 'r')
  File "/usr/local/lib/python3.6/site-packages/keras/utils/io_utils.py", line 197, in __init__
    'Received: {}.'.format(type(path)))
TypeError: Required Group, str or dict. Received: <class 'pathlib.PosixPath'>.

..................................

Thank's in advance ......

**Comment by giesselmann** [comment]
same error here.

**Comment by giesselmann** [comment]
it happens, if you use the --rapid or --native flags, if you specify the models -s / -e manually, it works.

**Comment by lowandrew** [comment]
I'm having the same issue, although the above workaround works for me too.

**Comment by nicoledel3** [comment]
What did you specify after the -s / -e flags? I'm trying to use the --rapid read start model, but I got the same error. Thank you!

**Comment by nicoledel3** [comment]
> What did you specify after the -s / -e flags? I'm trying to use the --rapid read start model, but I got the same error. Thank you!
To clarify I specified -s SQK-RBK004 and got that SQK-RBK004 didn't exist.

**Comment by lowandrew** [comment]
I downloaded the [rapid read model](https://github.com/rrwick/Deepbinner/blob/master/models/SQK-RBK004_read_starts) from this repo and then gave the path to that. Alternatively, the pull request that's waiting to be merged fixes things so that  `--rapid` and `--native` can be used. You'd just have to clone that and then `pip install -e .` from the base of the repository.

**Comment by ttubb** [comment]
For anyone finding this thread: You can make a small change in deepbinner.py by yourself, explained here: https://github.com/eclarke/Deepbinner/commit/00e9ff93a0ffa21f583e258cd071fec00ae4f0a8 .
