### ISSUE TITLE
bin step failure

### ISSUE THREAD

**Issue by Freemacl** [rrwick/CNN-Demultiplexer#29]
We converted multi fast5 to single fast5 and have successfully run everything up until this last bin step. We get this same error after it has processed approximately 200,000 reads (3.5 Gbs). Tried on multiple different installs (git dist, conda) with the same result.

```
$ deepbinner bin --classes classifications_edited --reads combined_fastq.gz --out_dir ~/Vault/PERSONAL-folders/Supriya/Nanopore_II_June25/demultiplexed_2/ 

Loading classifications... done
2,088,654 total classifications found

Making output directory: /home/imss/Vault/PERSONAL-folders/Supriya/Nanopore_II_June25/demultiplexed_2/

Traceback (most recent call last):
  File "/home/imss/tools/anaconda3/envs/dbinner/bin/deepbinner", line 10, in <module>
    sys.exit(main())
  File "/home/imss/tools/anaconda3/envs/dbinner/lib/python3.7/site-packages/deepbinner/deepbinner.py", line 64, in main
    bin_reads(args)
  File "/home/imss/tools/anaconda3/envs/dbinner/lib/python3.7/site-packages/deepbinner/bin.py", line 32, in bin_reads
    write_read_files(args.reads, classifications, out_filenames, input_type)
  File "/home/imss/tools/anaconda3/envs/dbinner/lib/python3.7/site-packages/deepbinner/bin.py", line 146, in write_read_files
    out_files[class_name].write(read_line_1)
KeyError: 'not found'

```

**Comment by jdeligt** [comment]
seems like a duplicate of #11 I've added a hotfix in pull request #30 that you can implement/pull if you want to continue
