### ISSUE TITLE
Issues using on CentOS

### ISSUE THREAD

**Issue by lab-rat-kid** [rrwick/CNN-Demultiplexer#33]
I have this working on Ubuntu, but now using through  ssh on cluster computers with centos I get the following errors:

```
-bash-4.1$ deepbinner realtime --in_dir fast5s/ --out_dir demulti_fast5/ --native
Using TensorFlow backend.

Traceback (most recent call last):
  File "/export/home/2141180e/downloads/anaconda3/bin/deepbinner", line 10, in <module>
    sys.exit(main())
  File "/export/home/2141180e/downloads/anaconda3/lib/python3.7/site-packages/deepbinner/deepbinner.py", line 69, in main
    realtime(args)
  File "/export/home/2141180e/downloads/anaconda3/lib/python3.7/site-packages/deepbinner/realtime.py", line 33, in realtime
    set_tensorflow_threads(args)
  File "/export/home/2141180e/downloads/anaconda3/lib/python3.7/site-packages/deepbinner/classify.py", line 418, in set_tensorflow_threads
    config = tf.ConfigProto(intra_op_parallelism_threads=args.intra_op_parallelism_threads,
AttributeError: module 'tensorflow' has no attribute 'ConfigProto'
```

**Comment by lab-rat-kid** [comment]
Fixed. Needs specifically tensorflow 1.15 to work.
