### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow'

### ISSUE THREAD

**Issue by jgonzalez10** [rrwick/CNN-Demultiplexer#35]
Hi!

I'm using Deepbinner because the previous program I used left many of my reads as 'unclassified'. But, no matter what I try to run I always get this error:

[jg2279@cbsugpu03 Deepbinner]$ deepbinner classify --rapid Raw_fast5
Using TensorFlow backend.
Traceback (most recent call last):
  File "/programs/Deepbinner-0.2.0/bin/deepbinner", line 11, in <module>
    load_entry_point('Deepbinner==0.2.0', 'console_scripts', 'deepbinner')()
  File "/programs/Deepbinner-0.2.0/lib/python3.6/site-packages/deepbinner/deepbinner.py", line 59, in main
    from .classify import classify
  File "/programs/Deepbinner-0.2.0/lib/python3.6/site-packages/deepbinner/classify.py", line 24, in <module>
    from keras.models import load_model
  File "/programs/Deepbinner-0.2.0/lib/python3.6/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/programs/Deepbinner-0.2.0/lib/python3.6/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/programs/Deepbinner-0.2.0/lib/python3.6/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/programs/Deepbinner-0.2.0/lib/python3.6/site-packages/keras/backend/__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "/programs/Deepbinner-0.2.0/lib/python3.6/site-packages/keras/backend/load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "/programs/Deepbinner-0.2.0/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

Help!! Thanks!!!

**Comment by MostafaYA** [comment]
Hi, I am not sure if this could help but you may try 
`python -m pip install tensorflow --user`

**Comment by MostafaYA** [comment]
**UPDATE**
python -m pip install tensorflow==1.15 --user

**Comment by gaferguz** [comment]
Hi @MostafaYA  and everyone, I am facing the same issue when i install tensorflow 2.0 version or higher, but then when I tried deepbinner using tensorflow==1.15 I get the following error:

```
$ deepbinner classify --rapid fast5_pass/ > classifications
Traceback (most recent call last):
  File "/Users/Comms/.local/lib/python3.7/site-packages/keras/__init__.py", line 3, in <module>
    from tensorflow.keras.layers.experimental.preprocessing import RandomRotation
ModuleNotFoundError: No module named 'tensorflow.keras.layers.experimental.preprocessing'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Comms/.local/bin/deepbinner", line 8, in <module>
    sys.exit(main())
  File "/Users/Comms/.local/lib/python3.7/site-packages/deepbinner/deepbinner.py", line 59, in main
    from .classify import classify
  File "/Users/Comms/.local/lib/python3.7/site-packages/deepbinner/classify.py", line 24, in <module>
    from keras.models import load_model
  File "/Users/Comms/.local/lib/python3.7/site-packages/keras/__init__.py", line 6, in <module>
    'Keras requires TensorFlow 2.2 or higher. '
ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`
```
What should I do?
