### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lfaino** [rrwick/CNN-Demultiplexer#9]
Dear Developper,
i got this error while tring to run Deepbinner.
can you help, please?

Cheers 
Luigi

lfaino@LabReverberi_PT ~/pant $ deepbinner realtime --in_dir 0 --out_dir demultiplexed_fast5s --rapid
Using TensorFlow backend.

2018-10-03 16:53:30.989411: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Loading /home/lfaino/.local/lib/python3.5/site-packages/deepbinner/models/SQK-RBK004_read_starts... Traceback (most recent call last):
  File "/home/lfaino/.local/bin/deepbinner", line 11, in <module>
    load_entry_point('Deepbinner==0.2.0', 'console_scripts', 'deepbinner')()
  File "/home/lfaino/.local/lib/python3.5/site-packages/deepbinner/deepbinner.py", line 69, in main
    realtime(args)
  File "/home/lfaino/.local/lib/python3.5/site-packages/deepbinner/realtime.py", line 33, in realtime
    out_dest=sys.stdout)
  File "/home/lfaino/.local/lib/python3.5/site-packages/deepbinner/classify.py", line 66, in load_and_check_models
    out_dest=out_dest)
  File "/home/lfaino/.local/lib/python3.5/site-packages/deepbinner/classify.py", line 90, in load_trained_model
    model = load_model(model_file)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/saving.py", line 417, in load_model
    f = h5dict(filepath, 'r')
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/io_utils.py", line 195, in __init__
    'Received: {}.'.format(type(path)))
TypeError: Required Group, str or dict. Received: <class 'pathlib.PosixPath'>.

**Comment by kjestradag** [comment]
hi !

same error here:

$ deepbinner realtime --in_dir fast5_example/ --out_dir demultiplexed_fast5s --rapid
Using TensorFlow backend.

Loading /home/karel/.local/lib/python3.6/site-packages/deepbinner/models/SQK-RBK004_read_starts... Traceback (most recent call last):
  File "/home/karel/.local/bin/deepbinner", line 11, in <module>
    load_entry_point('Deepbinner==0.2.0', 'console_scripts', 'deepbinner')()
  File "/home/karel/.local/lib/python3.6/site-packages/deepbinner/deepbinner.py", line 69, in main
    realtime(args)
  File "/home/karel/.local/lib/python3.6/site-packages/deepbinner/realtime.py", line 33, in realtime
    out_dest=sys.stdout)
  File "/home/karel/.local/lib/python3.6/site-packages/deepbinner/classify.py", line 66, in load_and_check_models
    out_dest=out_dest)
  File "/home/karel/.local/lib/python3.6/site-packages/deepbinner/classify.py", line 90, in load_trained_model
    model = load_model(model_file)
  File "/home/karel/.local/lib/python3.6/site-packages/keras/engine/saving.py", line 417, in load_model
    f = h5dict(filepath, 'r')
  File "/home/karel/.local/lib/python3.6/site-packages/keras/utils/io_utils.py", line 197, in __init__
    'Received: {}.'.format(type(path)))
TypeError: Required Group, str or dict. Received: <class 'pathlib.PosixPath'>.

I already compile in all ways, git, pip[3], conda.. install all the requirements too, python packages etc.

help please !! :)

**Comment by bartailey** [comment]
I had this issue as well when running deepbinner 0.2.0 and cuda 9.0.

**Comment by lfaino** [comment]
Did you solve the problem? If yes, how?

Cheers 
Luigi

**Comment by bazante1** [comment]
https://github.com/eclarke/Deepbinner/commit/00e9ff93a0ffa21f583e258cd071fec00ae4f0a8

This worked for me!

**Comment by lfaino** [comment]
it works for me too

**Comment by themouldinator** [comment]
@lfaino could you explain how you did it? I've been trying for the past 3 hours with no success

**Comment by bazante1** [comment]
@themouldinator  You should change this in the deepbinner.py (Remove 2 lines, Add 2 lines)
https://github.com/eclarke/Deepbinner/commit/00e9ff93a0ffa21f583e258cd071fec00ae4f0a8
And make sure the file you edit is the same one you later gonna use, or run the your/folder/deepbinner-runner.py from the folder where you changed the file.

**Comment by themouldinator** [comment]
@bazante1 Thanks!
Just to clarify for anyone reading this in the future, the deepbinner.py script you need to edit is in the Deepbinner/deepbinner directory NOT the one in Deepbinner/guess they wanted to get it pretty deep in there! hehe
The text to edit is right at the bottom of the script.
Good luck and thanks for all the help guys!

**Comment by abgvg9** [comment]
Hi,

My lab group is currently trying to use deepbinner to demultiplex our fast5 files that we collected. We have encountered the same errors that were addressed in this thread. We went and modified the deepbinner.py file with the 2 line changes, so that the return type was changed to a string. However, we are still getting the same errors. We are not super familiar with how python works. Is there any form of recompilation that we need to do so the the program is up to date with running the deepbinner executable, or is it possible that there is something else wrong? The following is what our error looks like after making those 2 line changes, as well as the command we are executing:

root@r06duvernelld:~/Deepbinner/deepbinner# deepbinner classify --native sample_reads.tar.gz > classifications
Using TensorFlow backend.
2018-12-04 11:36:25.680182: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
Loading /usr/local/lib/python3.6/dist-packages/deepbinner/models/EXP-NBD103_read_starts... Traceback (most recent call last):
  File "/usr/local/bin/deepbinner", line 11, in <module>
    load_entry_point('Deepbinner==0.2.0', 'console_scripts', 'deepbinner')()
  File "/usr/local/lib/python3.6/dist-packages/deepbinner/deepbinner.py", line 60, in main
    classify(args)
  File "/usr/local/lib/python3.6/dist-packages/deepbinner/classify.py", line 36, in classify
    load_and_check_models(args.start_model, args.end_model, args.scan_size)
  File "/usr/local/lib/python3.6/dist-packages/deepbinner/classify.py", line 66, in load_and_check_models
    out_dest=out_dest)
  File "/usr/local/lib/python3.6/dist-packages/deepbinner/classify.py", line 90, in load_trained_model
    model = load_model(model_file)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 417, in load_model
    f = h5dict(filepath, 'r')
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/io_utils.py", line 197, in __init__
    'Received: {}.'.format(type(path)))
TypeError: Required Group, str or dict. Received: <class 'pathlib.PosixPath'>.
